name: Build and Publish StoryBook

on:
    push:
        branches:
            - main

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Cache node modules
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.npm
                      ./node_modules
                  key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-npm-

            - name: Extract Node.js version from .nvmrc
              id: extract-node-version
              run: echo "::set-output name=node_version::$(cat .nvmrc)"

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ steps.extract-node-version.outputs.node_version }}

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build-storybook

            - name: Setup Deploy
              run: |
                echo '{"hosting":{"public":"storybook-static","ignore":["firebase.json","**/.*","**/node_modules/**"],"rewrites":[{"source":"**","destination":"/index.html"}]}}' > firebase.json

            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                repoToken: '${{ secrets.GITHUB_TOKEN }}'
                firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AQUA_FUSION_DESIGN }}'
                channelId: live
                projectId: aqua-fusion-design
